### ISSUE TITLE
Automated Word to XML 

### ISSUE THREAD

**Issue by yowill** [18F/eregs-platform#41]

**Comment by yowill** [comment]
A day of research and 2 days of implementation

**Comment by cmc333333** [comment]
@Journerdism very preliminary tests look positive. Would you mind reaching out to EPA and ATF (maybe FEC?) to get more example input documents?

We want proposed rules (they can be from the past) as the Word documents. These should be the same documents that the agencies send over the the Federal Register.

**Comment by yowill** [comment]
@cmc333333 Sure will do.

**Comment by yowill** [comment]
@cmc333333 6 coming in the email tubes shortly

**Comment by cmc333333** [comment]
Pulled several from CFPB, EPA, and ATF. As these docs aren't official, we'll just store them in Google Drive: https://drive.google.com/drive/folders/0ByNRVH8rhs0YQ2NmUE5vZVp2OE0

Status update: I briefly played with https://python-docx.readthedocs.io/en/latest/ on one of those documents and had good luck. Not enough time to describe this as complete, though.

**Comment by bmcguirk** [comment]
@Journerdism @cmc333333 - Assuming that most of these docs get written in .docx (thus the need for this issue), and I assume most regulation documents have extensively-tracked changes, do you have any plans for showing like a revision history / `diff` of different versions of the regs? 

Great tool, btw! Keep up the awesome work!

**Comment by cmc333333** [comment]
Welcome @bmcguirk! 

We do implement a history of the regulation via diffs by comparing the parsed regulation trees (effectively comparing whole versions of regulations). For example, see [this diff](https://atf-eregs.apps.cloud.gov/diff/555-11/2014-18842/2015-25190?from_version=2015-25190#555-11-p2162297120) of some versions of 27 CFR 555. This strategy works well as we're comparing "official" sources of the CFR rather than the documents internal to agencies. The docx conversion work here is focused on importing "proposed rules" as opposed to whole CFRs; our goal is to make the _initial_ conversion automated and allow for manual fixups where needed. There's less need for tracking changes here, but it's a good reminder for related work.

That said, I'll be sure to update this issue with our progress. Let us know if you have some free cycles we could borrow 😄

**Comment by bmcguirk** [comment]
@cmc333333 - Wo! Ok, didn't follow the "regulation timeline" feature. Very cool! 

And for document conversion, I don't actually know anything better than [Pandoc](http://pandoc.org/). Have you checked that out yet?
