### ISSUE TITLE
CFR viewer drawer tweaks

### ISSUE THREAD

**Issue by cmc333333** [18F/eregs-platform#52]
@jehlers to add. Screenshots appreciated, if there's time

**Comment by jehlers** [comment]
## CFR Drawer

Since the subparts are not clickable, and the sections are, we want to emphasize them and visually push back the subparts so the user clearly understands the difference. The current ATF visual styles are generally what we want to aim for:

<img width="354" alt="screen shot 2016-08-25 at 10 27 29 am" src="https://cloud.githubusercontent.com/assets/4267825/17972968/9c6ed9ba-6aae-11e6-8773-0481d0e8dd75.png">
- [x] The section text should be black. 
  - [x] The section numbers are larger and bold (or semibold whatever font we are using), and 
  - [x] The titles are smaller and regular (a lighter weight for added contrast and easier skimming).
- [x] The subparts should be as light a gray we can go as accessibly possible. Usually that's #767676. 
  - [x] And a smaller font size (same size as the title text) usually 12-14px depending on the font. I _think_ source sans can only go to 14px and lato can go down to 12px because the x-height is larger and the bowls of the letters are more geometric and wider. :nerd: [Will explain the type hierarchy stuff in another issue TBD]

## Tabs

We want to match the new white tabs in N&C:

<img width="244" alt="screen shot 2016-08-25 at 10 32 02 am" src="https://cloud.githubusercontent.com/assets/4267825/17973859/f5ac6652-6ab1-11e6-966c-a0b22890e79c.png">

Here is normal eRegs tabs as they are now:

<img width="244" alt="screen shot 2016-08-25 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/4267825/17973434/750c3104-6ab0-11e6-8ab1-2a583ce390d3.png">
- [x] The ON tab icons should match the color of the title of the tab. So in this case the blue of the "TABLE OF CONTENTS" should match the outline icon in the upper tab.

## Preamble tab

The preamble tab should look a little different and act a little different than the CFR tab because the document it is controlling is structured differently. The way it is structured and is working currently in the N&C tool is correct, except: 
- [x] All the text should be black to match the black section text in the CFR tab (the clickable text as opposed to the unclickable subparts).

For background, which may or may not be helpful... 

**The parent sections in the preamble:**
- Preamble Introduction
- I. General information

Should match the style of the section _numbers_ in the CFR tab, ie "§478.21"

**The lower sections:**
- A. Does this action apply to me?
- B. What action is the agency taking?

Should match the style of the section _titles_ in the CFR tab, ie "Forms prescribed."

**Comment by jehlers** [comment]
For got one CFR tab... 

## CFR tab in N&C

We want to make sure this tab matches the normal CFR tab mentioned above. However, because there is more than one regulation present in this tab, it is visually structured a little differently.

Here is what it looks like now in the N&C tool:

<img width="244" alt="screen shot 2016-08-25 at 11 17 45 am" src="https://cloud.githubusercontent.com/assets/4267825/17975021/3366b106-6ab6-11e6-8730-3a8be1b4cd17.png">

We want it to match the ATF-like design above. So my comments here are the same as my comments above for the "CFR Drawer:"
- [x] The section text should be black. (In this case, "Authority," and "§ 262.24 Use of the electronic manifest," etc...)
  - [ ] **NICE TO HAVE:** The section numbers are larger and bold (or semibold whatever font we are using), and
  - [ ] **NICE TO HAVE:** The titles are smaller and regular (a lighter weight for added contrast and easier skimming). _(I'm pretty sure the sections are already the size and weight they should be. The update here would be pulling out the § section numbers and putting them on a separate line just like the normal CFR tab.)_
- [x] The regulation citations ("40 CFR 262," etc...) should match the subparts in the normal CFR viewer because they are not clickable. Therefore, they should be as light a gray we can go as accessibly possible. Usually that's #767676.
  - [x] And a smaller font size (same size as the title text) - whatever they subparts normally are.

**Comment by cmc333333** [comment]
We hit all of this except for some of the nice-to-have's in https://github.com/eregs/regulations-site/pull/461
