### ISSUE TITLE
2 LESS -> SASS conversion

### ISSUE THREAD

**Issue by cmc333333** [18F/eregs-platform#6]
Includes discussion with FEC folks and implementation of conversion

**Comment by xtine** [comment]
Steps:
- [x] 1. run the npm less2sass script that will do a basic conversion on all less files to sass (in a new `scss` directory)
- [x] 2. inspect the compiled scss and identify issues that need manual conversion
- [x] 3. document each type of manual update needed
- [x] 4. compile converted scss files and compare with original less generated `style.css` to see if there are any differences
- [x] 5. update `compile_frontend` management command to compile scss files instead of less
- [x] 6. run `compile_frontend` and visual regression tests, as well as some manual browsing testing to see if there are style regressions from conversion that can be fixed.

**Comment by xtine** [comment]
## LESS to Sass stylesheet conversion rundown

Before running the conversion with the `less2sass.sh` (<a href="https://github.com/xtine/regulations-site/blob/less2sass/regulations/static/regulations/css/less2sass.sh">source</a>) script I wrote, I modified a few less stylesheets to make the transition easier:
- `main.less`: move the base-variables import to the top (<a href="https://github.com/xtine/regulations-site/commit/d8ef2e5cf9983508e3ad245df67d6055c123fdd3">change</a>)
- remove IE7 support in `cf-icons.less` (<a href="https://github.com/xtine/regulations-site/commit/f7db8bcbfef3e1ff46dc920a563d36bf1719ffed">change</a>)
- `typography.less`: change ampersand rules on dataTables (<a href="https://github.com/xtine/regulations-site/commit/85df415249ba194419f3e3c670b7308817321ace">change</a>)
- `module/interpretations.less`: add a missing semicolon (<a href="https://github.com/xtine/regulations-site/commit/464da5a80e5674997281657ca19dab979e232ba3">change</a>)
- `module/header.less`: in sass, extensions are not allowed in media queries, so I added the cf-icon properties in manually on a the a:after selector. (<a href="https://github.com/xtine/regulations-site/commit/9059e56f60a4728df2699e26dd954b786427b1aa">change</a>)

The `less2sass.sh` script downloads/runs the less2sass npm package which does a quick conversion of less files and additionally runs regexes for additional conversion fixes.

Then to get the `compile_frontend` command to compile the scss files:
- add grunt-contrib-sass 1.0.0 to `package.json` (<a href="https://github.com/xtine/regulations-site/commit/921eebd8f0795f13641622468328bb649cba959c">change</a>)
- add sass task to `Gruntfile.js` (<a href="https://github.com/xtine/regulations-site/commit/720a9c77fa6e04974fa0f5f94abf1df4bb1ea75e">change</a>)
