### ISSUE TITLE
Put a password on the EPA site for the closing of the ATO

### ISSUE THREAD

**Issue by yowill** [18F/eregs-platform#61]
(After Bill approves it)

Add language for people who don't have access to the site to go to the EPA site or federal register

**Comment by jehlers** [comment]
Instead of password protecting the site. We are moving the homepage over to a static Federalist site with a few minor updates:
- [x] Update copy in the top section to match the image TBD
- [x] eRegulations in the header should link to eregs.github.io
- [x] Take out expandable about “other ways to comment”
- [x] In “we want to hear from you” replace the github repository sentence with: "To give feedback on this tool, visit eregs.github.io or email us at eregs@gsa.gov."

**Comment by jehlers** [comment]
Copy and slightly shifted design for the first check mark above:

![screen shot 2016-10-13 at 4 18 32 pm](https://cloud.githubusercontent.com/assets/4267825/19365420/ae4a2922-9160-11e6-845d-7535a5aafd9c.png)

The comment period is closed for: 

If you are looking to read this rule, you can read it on [EPA’s website](https://www.epa.gov/hwgenerators/hazardous-waste-electronic-manifest-system-e-manifest), in the [Federal Register](https://www.federalregister.gov/documents/2016/07/26/2016-15845/hazardous-waste-management-system-user-fees-for-the-electronic-hazardous-waste-manifest-system-and), or view the [official docket folder](https://www.regulations.gov/docket?D=EPA-HQ-OLEM-2016-0177). 

But, if you are interested in making it easier for your agency to handle public comments, keep reading! 

The eRegulations Notice & Comment platform:  Read, understand, and comment on new proposed laws.

**Comment by cmc333333** [comment]
http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/epa-notice-landing/

Next step is to get the domain name setup.

**Comment by cmc333333** [comment]
Talking with Jez and Will Slack about this on Monday to figure out who has usa.gov

**Comment by cmc333333** [comment]
https://github.com/18F/federalist/issues/551 to track.

**Comment by cmc333333** [comment]
This is live now.
